// Code generated by generate-reset; DO NOT EDIT.

package model

import (
	"sync"
)

func (m *Metrics) Reset() {

	m.ID = ""

	m.MType = ""

	m.Delta = nil

	m.Value = nil

	m.Hash = ""

}

func (r *RuntimeMetric) Reset() {

	r.Metrics = nil

	r.mx = sync.RWMutex{}

}

func (m *MemStorage) Reset() {

	m.mx = sync.RWMutex{}

	m.metrics = m.metrics[:0]

}

func (u *UtilMetric) Reset() {

	u.TotalMemory = 0

	u.FreeMemory = 0

	u.CPUUtilization1 = 0

}
