package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

type Field struct {
	Name      string
	Type      types.Type
	Zero      string
	IsMap     bool
	HasReset  bool
	IsSlice   bool
	IsPointer bool
}

type StructInfo struct {
	Name    string
	Fields  []Field
	Recv    string
	Imports map[string]string
}

const genTemplate = `// Code generated by generate-reset; DO NOT EDIT.

package {{.Package}}

{{if .Imports}}
import (
{{range $path, $alias := .Imports}}    "{{$path}}"
{{end}}
)
{{end}}

{{range .Structs}}
{{ $struct := . }}
func ({{.Recv}} *{{.Name}}) Reset() {
	{{range .Fields}} 
        {{if .HasReset}} 
            {{if .IsPointer}}
                if {{ $struct.Recv }}.{{.Name}} != nil { 
                    {{ $struct.Recv }}.{{.Name}}.Reset() 
                }
            {{else}}
                {{ $struct.Recv }}.{{.Name}}.Reset()
            {{end}}
        {{else if .IsSlice}} 
            {{ $struct.Recv }}.{{.Name}} = {{ $struct.Recv }}.{{.Name}}[:0]
        {{else if .IsMap}} 
            {{ $struct.Recv }}.{{.Name}} = nil
        {{else}} 
            {{ $struct.Recv }}.{{.Name}} = {{.Zero}}
        {{end}}
	{{end}}
}
{{end}}
`

var (
	tmpl = template.Must(template.New("reset").Parse(genTemplate))
)

func processPackage(pkg *packages.Package) {
	var structs []StructInfo

	for i, file := range pkg.Syntax {
		f := pkg.CompiledGoFiles[i]

		if strings.HasSuffix(f, ".gen.go") {
			continue
		}

		currentPkgPath := pkg.PkgPath

		ast.Inspect(file, func(n ast.Node) bool {
			gen, ok := n.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				return true
			}

			if gen.Doc == nil {
				return true
			}

			for _, comment := range gen.Doc.List {
				if strings.TrimSpace(comment.Text) == "// generate:reset" {

					for _, spec := range gen.Specs {
						ts, ok := spec.(*ast.TypeSpec)
						if !ok {
							continue
						}

						if _, ok := ts.Type.(*ast.StructType); ok {
							obj := pkg.Types.Scope().Lookup(ts.Name.Name)
							if obj != nil {
								info := extractStructInfo(ts.Name.Name, pkg.Types.Scope().Lookup(ts.Name.Name), currentPkgPath)
								structs = append(structs, info)
							}
						}
					}
					return true

				}
			}

			return true
		})
	}
	if len(structs) > 0 {
		if err := generateResetFile(pkg, structs); err != nil {
			log.Printf("ошибка генерации reset.gen.go in %s: %v", pkg.PkgPath, err)
		}
	}
}

func generateResetFile(pkg *packages.Package, structs []StructInfo) error {

	if len(pkg.CompiledGoFiles) == 0 {
		return nil
	}

	dir := filepath.Dir(pkg.CompiledGoFiles[0])

	filename := filepath.Join(dir, "reset.gen.go")

	allImports := make(map[string]string)
	for _, s := range structs {
		for imp := range s.Imports {
			allImports[imp] = ""
		}
	}

	var buf bytes.Buffer
	data := struct {
		Package string
		Imports map[string]string
		Structs []StructInfo
	}{
		Package: pkg.Name,
		Structs: structs,
		Imports: allImports,
	}

	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("ошибка форматирования: %w\n%s", err, buf.String())
	}

	return os.WriteFile(filename, formatted, 0644)
}
